language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: Gz0fFuituXsrchIqAFyBEbr9VcgNEZG1nmaCEK/MT1465G6685GgfvlNYvNojpwHBFFoyJU2FMuWzUTVII17K6zZq+3i4QKbdPtnDmqZ5KtikMcUXvrS0SZ6kuF6Ai1IcJwOvINqss5wtxsSnfj6MNILFfwHyOoMeYN9dX7B0zKSyWREKt2mTrd2ko59A1QPJTEw7DhE6BAF1YW+T1kv693hQkhaLv40ohXkjrGKntDbY8Do4Y1FPOMn4oqGA71/MJTZV8yxvUf8JwZGccZGZRkL9hie5VbHgMCMIfoMcTvbXA3S74TuC5ZSlkO+zDtE0GCpG5/l+LTqd2GQPrMq8QDe0ocqJXOV/XGw1AHb8xH8xjdUCLAeLlWbiaHmAKqX9pRgcv8Igu8p30nIogHUA0fie5T3WzkJFCsqJZxXXAIBlLPXkM11o+I4mhmKQxlGTpxrGsxAePdjYG/e6cvo2Sl9zQfe2U56kZsdMhBaY0njQn0aS3pReyI5az2AmV0raePrCChOP2GzUyf1Unk/Zx2tcRn6/ba3ULJXZJtfJ5xO2LXH21S+0ED5Ukb+7SXuEhI6YiCq9tF1Ku5kg4Kc0Xt/8hTwjf6zj2VHmMvv1npIMqLe7Ll8bTn+vAx/gqX5vhacyF6bzPZspyirairtQuJIeTynY2trNk1O4EWUUIw=
  - secure: e6K9wOFvuRPVlIE8uX6Mkg8cIuOJ3MTygosvbZ/aqPiM8HbBikMF+nrsa1Gy2Iq0MSoUyGOB9ugUsnI7LyvWzFlnUXIiWez9zoV7U8bFDo2SsN3gxrgVK6rU+ADXJWbfAxyMJ3l2s9bWRbXnv6D7zrU6p5yuNWZE28gG2UJ5ndKIlLU//9gNUAOPhBGHsLtiTre9rPPvj2qHt7Kc4xlk85Se91I33C06fShqYyXoKa4cOjZ2ecqtUnLdsVEn+FBzLRbwO3GH+sJRZ+f5nTv0Jex7pwub3yYpn48dyfFXZXLOarfoJ3d0NEggPwcDJr7oPwX+Sb63rD7yvC+Db2+YUuSjdZQcvnWsYPBacOy7XJ4L1+ou6Kv28xSskP7/LPkr43hL9pH2V8Z/OjElOyIrehHP9wuJHmGaqb8prV+INM5lLkTrhgmSNq4alTOWGAZWpXJOJ4HdMJBo6Y6FrNcNGnPrjpht88iAHmgylDJnRNPWLoH9jZ63f0IAL6l3ug1aWcwCr2BKnh5dVHoemsPfP68emhaYjJATpQiU65Do/BWCnh8iW+fzT3CCN1KrBxpSBdRfaAADLICwrTqSPnx2gj+wo3KEY0T0P3eIC5PLbW8kBp9rAJh77h1krt+mS/zsixMKpX2u3/JAYLF79b0tu3sRr3InV2UnpDDyfd7hdCw=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
