language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: xDp4Y+KT3q+K/cwg/ACSSxa5w2JYOHUjiVc3Yh7t+ThH/28EbCJpCDZqbuOZHgiZwroOokeTuVr8aEnLtD8t0ujIcoEBBNdj+rSG7h9jIS95T21RlkiHWLCjHyw4HhGqJRbx3Jd9LSxM2ojvIwRyqmn7Iqo2PWDL82xQ74I0JiWXAAvTMm1jOlvHogldZSb1DJe4jUbs+CNch+V8b5NRAJ3cZ/FX1dwV+Ftu42FX2Us6+yNYuhOLygL8Oz9ECXKmDaJBajMIghW6ogA6iM7JaTGS+K1ZTJCORoAZRJrAEvZ+ayQG80HQc69opqnJM3a8uiKlt8lC7Z5SNwi9EmQfVwMkNWILqVNn5EXjp/eHgp85FlT+q7ru7Lc3x2hcDUBmlOGyHjuraoN49/efewvJOcr8+dCJ/XfBAgqfxf1fVhWhiwc/wqus6ltfk8ubk/cY5boK/ktL1pOwSMPdIVVodb0D1O08QugiG2NY2dOiW9mabZpuEW7arwJJB+VkTtXCN/CjFXgtq9CNGuekIyptT4MmVOd1ZraT4k0XS/5ahpdB+/SwE3hZafvrvepUEfEOEVTgEhZutafyNG+MAA1+MyBE9Ov+Q+0xlv6poQbccbHpK217Z1mdP7bXVSpJSvUSd4aFTpE/VcsYKJylZ0mNLvwCMHFcivur3fFiw/IR05I=
  - secure: DQNFXVnHndCfuf2JiIgM7yhmttiVw/tP5x/lEYZQJtKc0ehh2lRziBXaIHCIZ4cjAZsUqCYnjLAwJhTE3WT+5RP/7HqW+es50oNaiM8pdZQgvuRPhNzo00V7ybS2Mis453QsGDKWhv11WubmKl6Lkq8IsHZ5OGqP4GGnBY5q/TgoT7ZbEDoolLpqA/ioF52FRXTS11odVl4p/cyIUW26ophlnidMB4if0E44c7OpTl6vEeSd7BfD65AF4LqjodJQjMFn8fcuH3DX/rDgWvidgNzmWowjDKcE5HBAriKKd92eDFOfcz9KrBPqUDDvCmIkpAqbrqvPWRnSmfee/WQv9IPA3c1FhiYaYzOGK+Qh4sDdiz9OkYxl8ceQyQ7z7pZ531Q/DBvLn7ciJiodg8XBtkGJSV+5b8vWjFCZKwHnzuZsw+9ueIf1ZQguoGM7hZbiocBrLuZ1iYqN5HBcvgONeaoo+FpH/VOQolZ+sDdp1vstY78PiFW1A/uP/aRKGCZ4CTw3yV43Mvi2x9qRQ9a+AmOjtBYyEsRt9DfwU+Hu+iKqfzyNdihnWcjxL+ahx9XM7fH66w6wiAMC+XgWcCNCyC8I65yGKgTtrke++l6VjMI4dwrleoI4KGS+aZBjFvnAPk0lBIRKMe/bFUfPBElYbppLXBpz4WJ2vs7azqJqivA=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
